// Phase 1 renderer — pure filesystem + string templating.
// Takes a build plan JSON, writes the text files the Pi needs on its
// boot partition (dietpi.txt + Automation_Custom_Script.sh).
//
// MUST stay logically identical to the browser-side dietpiTxt() and
// automationScript() in app/src/output.js. To stay in sync, the
// browser builds a plan via buildPlan() and either:
//   (a) renders inline (current path) for the live preview, OR
//   (b) downloads plan.json so this CLI can render it on a CI box.
//
// Both paths produce byte-identical output for the same manifest.

import { promises as fs } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

function ts() { return new Date().toISOString(); }

// ── Templates — kept as JS template literals so they're easy to
//    diff against app/src/output.js. Changing either side requires
//    a parallel change here.

function renderDietpiTxt(plan) {
  const m = plan.manifest;
  const headless = plan.env.headless;
  const wifi = m.network.wifi_ssid
    ? `AUTO_SETUP_NET_WIFI_ENABLED=1
AUTO_SETUP_NET_WIFI_COUNTRY_CODE=AU
AUTO_SETUP_NET_WIFI_SSID=${m.network.wifi_ssid}
AUTO_SETUP_NET_WIFI_KEY=${m.network.wifi_password || ''}`
    : `AUTO_SETUP_NET_WIFI_ENABLED=0`;
  const software = headless
    ? '# Headless mode — no Chromium, no LXDE.'
    : `AUTO_SETUP_INSTALL_SOFTWARE_ID=113
AUTO_SETUP_INSTALL_SOFTWARE_ID=23`;

  return `# Ark — rendered ${ts()} from plan ${m.identity.name}
AUTO_SETUP_LOCALE=en_AU.UTF-8
AUTO_SETUP_KEYBOARD_LAYOUT=au
AUTO_SETUP_TIMEZONE=${m.software.timezone}
AUTO_SETUP_HEADLESS=${headless ? 1 : 0}
AUTO_SETUP_ACCEPT_LICENSE=1
AUTO_SETUP_AUTOMATED=1
AUTO_SETUP_NET_HOSTNAME=${m.network.hostname}
AUTO_SETUP_GLOBAL_PASSWORD=${m.software.root_password}

${wifi}

${software}

AUTO_SETUP_AUTOSTART_TARGET_INDEX=11
SURVEY_OPTED_IN=0
AUTO_SETUP_NET_USESTATIC=0
SOFTWARE_CHROMIUM_AUTOSTART_URL=${m.kiosk.url || ''}
SOFTWARE_CHROMIUM_RES_X=1920
SOFTWARE_CHROMIUM_RES_Y=1080
`;
}

function renderAutomationScript(plan) {
  const m = plan.manifest;
  const headless = plan.env.headless;

  const sshKeys = (m.network.ssh_pubkeys && m.network.ssh_pubkeys.length > 0)
    ? `mkdir -p /root/.ssh
chmod 700 /root/.ssh
cat > /root/.ssh/authorized_keys <<'KEYS'
${m.network.ssh_pubkeys.join('\n')}
KEYS
chmod 600 /root/.ssh/authorized_keys
systemctl enable ssh 2>/dev/null || true
systemctl restart ssh 2>/dev/null || true
`
    : '';

  if (headless) {
    return `#!/usr/bin/env bash
# Ark — rendered ${ts()} for ${m.identity.name} (HEADLESS)
set -euo pipefail
${sshKeys}
echo "Ark headless setup complete — ${m.identity.name}."
`;
  }

  const blank  = m.kiosk.disable_blanking ? `xset -dpms s off s noblank >/dev/null 2>&1 || true\n` : '';
  const cursor = m.kiosk.hide_cursor ? `apt-get install -y unclutter >/dev/null\n` : '';
  const rotate = m.kiosk.rotation && m.kiosk.rotation !== 'normal'
    ? `mkdir -p /etc/X11/xorg.conf.d
cat > /etc/X11/xorg.conf.d/40-rotate.conf <<XORG
Section "Monitor"
  Identifier "HDMI-1"
  Option "Rotate" "${m.kiosk.rotation}"
EndSection
XORG
` : '';
  const reload = m.kiosk.auto_reload_min > 0
    ? `apt-get install -y xdotool >/dev/null
(crontab -l 2>/dev/null; echo "*/${m.kiosk.auto_reload_min} * * * * DISPLAY=:0 xdotool key F5 >/dev/null 2>&1") | crontab -
` : '';

  return `#!/usr/bin/env bash
# Ark — rendered ${ts()} for ${m.identity.name}
set -euo pipefail
${sshKeys}${cursor}${blank}${rotate}${reload}
mkdir -p /var/lib/dietpi/dietpi-autostart
cat > /var/lib/dietpi/dietpi-autostart/custom.sh <<'KIOSK'
#!/usr/bin/env bash
while ! pgrep -x Xorg >/dev/null 2>&1 && ! pgrep -x Xwayland >/dev/null 2>&1; do sleep 1; done
export DISPLAY=\${DISPLAY:-:0}
${m.kiosk.hide_cursor ? 'unclutter -idle 0 -root &\n' : ''}
chromium-browser \\
  ${m.kiosk.fullscreen ? '--kiosk \\\n  ' : ''}--noerrdialogs \\
  --disable-infobars \\
  --disable-translate \\
  --disable-features=TranslateUI \\
  --check-for-update-interval=31536000 \\
  --no-first-run \\
  --start-fullscreen \\
  --start-maximized \\
  --user-data-dir=/var/lib/chromium-kiosk \\
  ${m.kiosk.url}
KIOSK
chmod +x /var/lib/dietpi/dietpi-autostart/custom.sh
echo "Ark setup complete — ${m.identity.name}. Reboot to launch."
`;
}


export async function renderPlan({ planPath, outDir }) {
  const planRaw = await fs.readFile(resolve(planPath), 'utf8');
  const plan = JSON.parse(planRaw);
  if (!plan.manifest) {
    // Legacy: some plans wrap the manifest at top level. Be liberal.
    throw new Error(`plan ${planPath} has no .manifest — was it generated by an older Ark UI?`);
  }
  const dest = resolve(outDir);
  await fs.mkdir(dest, { recursive: true });

  const dietpi  = renderDietpiTxt(plan);
  const script  = renderAutomationScript(plan);
  const planOut = JSON.stringify(plan, null, 2);

  await fs.writeFile(join(dest, 'dietpi.txt'), dietpi);
  await fs.writeFile(join(dest, 'Automation_Custom_Script.sh'), script, { mode: 0o755 });
  await fs.writeFile(join(dest, 'build-plan.json'), planOut);

  return {
    files: [
      join(dest, 'dietpi.txt'),
      join(dest, 'Automation_Custom_Script.sh'),
      join(dest, 'build-plan.json'),
    ],
  };
}
